@startuml

actor ApplicationUser as u
participant Browser as b
participant Application as app
participant Database as db

u -> b: нажатие на кнопку 'Регистрация'
b -> app: получение страницы регистрации
app -> app: генерация формы
app --> b: форма возвращается клиенту
b --> u: форма отображается пользователю
u -> b: пользователь заполняет форму, \n нажимает на кнопку 'Создать аккаунт'
b -> app: данные формы передаются на сервер
app -> app: валидация данных
app -> db: регистрация нового пользователя
db --> app: пользователь успешно сохранен
app -> app: генерация токена
app --> b: токен возвращается клиенту
b -> b: токен сохраняется в браузере
b -> u: пользователю отображается 'главная' страница

u -> b: пользователь переходит по страницам сайта
b -> app: в заголовках запроса передается токен
app -> app: валидация токена
app --> b: запрос обрабатывается согласно правам пользователя
b -> u: пользователю отображается доступный ему комнтент



@enduml